# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai_blog',
                'doc_host': 'https://jaydrennan.github.io',
                'git_url': 'https://github.com/jaydrennan/fastai_blog',
                'lib_path': 'fastai_blog'},
  'syms': {'fastai_blog.core': {'fastai_blog.core.foo': ('core.html#foo', 'fastai_blog/core.py')}}}
